import { Container } from "@mui/material";
import Button from "@mui/material/Button";
import Head from "next/head";

export default function Home() {
    const Icon = ({ color }: { color?: string }) => {
        return (
            <svg width="15" height="11" viewBox="0 0 15 11" fill={color} xmlns="http://www.w3.org/2000/svg">
                <path d=
                    "M7.5 0.25C3.7284 0.25 0.5 4.252 0.5 5.5C0.5 6.8065 2.9822 10.75 7.5 10.75C12.0178 10.75 14.5 
                    6.8065 14.5 5.5C14.5 4.252 11.2716 0.25 7.5 0.25ZM7.5 7.75C7.08466 7.75 6.67865 7.61804 6.3333 7.37081C5.98796 7.12357 5.7188 6.77217 
                    5.55985 6.36104C5.40091 5.9499 5.35932 5.4975 5.44035 5.06105C5.52138 4.62459 5.72139 4.22368 
                    6.01508 3.90901C6.30877 3.59434 6.68295 3.38005 7.09031 3.29323C7.49767 3.20642 7.91991 3.25097 8.30364 3.42127C8.68736 3.59157 9.01534 3.87996 9.24609 
                    4.24997C9.47684 4.61998 9.6 5.05499 9.6 5.5C9.6 6.09674 9.37875 6.66903 8.98492 7.09099C8.5911 7.51295 8.05695 7.75 7.5 7.75Z" fill={color} />
            </svg>
        );
    }
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Container component="main" maxWidth="xs" sx={{ display: "flex", flexDirection: "column", border: 3, boxShadow: 3, pb: 2 }}>
                <main>
                    <h1>Hello World!</h1>
                    <Button variant="outlined" sx={{ bgcolor: "#000", "&:hover": { bgcolor: "blue" } }}> Hazme click </Button>
                    <br />
                    <Button startIcon={<Icon />} variant="contained" disabled={false} sx={{
                        bgcolor: "#FF6319", color: "#fff", border: 3, borderColor: "#FF6319", borderRadius: "8px" ,
                        "& svg": { fill: "#fff" },
                        "&:hover": {
                            bgcolor: "#8A2C0D", borderColor: "#FF9361",color: "#FFC4A8",
                            "& svg": { fill: "#FFC4A8" }
                        },
                        "&:disabled": {
                            bgcolor: "#6B7280", color: "#111928",
                            "& svg": { fill: "#111928" }
                        }
                    }}> Ver detalle </Button>

                </main>
            </Container>
        </>
    );
}
